services:
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - scrobbler-net
    command: ["redis-server", "--loglevel", "warning"]

  scrobbler:
    image: ghcr.io/ernestohegi/scrobbler:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - scrobbler-net
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    dns:
      - 1.1.1.1
      - 1.0.0.1

volumes:
  redis-data:

networks:
  scrobbler-net:
    driver: bridge
